export const GET_ALL_USERS = "GET_ALL_USERS"
export const ADD_USER = "ADD_USER"
export const SELECT_USER_ID = "SELECT_USER_ID"
export const EDIT_USER = "EDIT_USER"
export const DELELE_USER = "DELELE_USER"
export const SELECT_USER = "SELECT_USER"
export const SELECT_USER_TO_EDIT = "SELECT_USER_TO_EDIT"
